# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    partition: 'RMC-C01-BATCH'
    timeout_min: 6000
    gpus_per_node: 1
    cpus_per_task: 4
    mem_gb: 10
    exclude: rmc-gpu03